name: C.Yao's blog
description: "It ain't what you don't know that gets you into trouble. <br>
			 It's what you know for sure that just ain't so."
meta_description: "Your New Jekyll Site, Blogging about stuffs"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://cnyao.me'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'http://cnyao.me'
author:         'Chunnan Yao'
