name: Chunnan Yao's blog
description: "Not Just Working"
meta_description: "Your New Jekyll Site, Blogging about stuffs"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: 'http://cnyao.me'
google_analytics: 'UA-75499921-1'
gems: [jekyll-paginate]
excerpt_separator: <!--more-->

# Details for the RSS feed generator
url:            'http://cnyao.me'
author:         'Chunnan Yao'
